import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { siteConfig } from "@/lib/site-config";
import { Reveal } from "@/components/PremiumMotion";
const panels=[
{n:"01",kicker:"WE FIX",title:"Bring the fault to us.",copy:"Blenders, kettles, irons, sockets, phones and laptops — diagnosed before the repair begins.",href:"/services",image:siteConfig.technicianPortrait,cls:"object-contain object-bottom"},
{n:"02",kicker:"WE SERVICE",title:"Keep good equipment working.",copy:"AC, fans and motors need technical attention before a small problem becomes a full breakdown.",href:"/services#ac-cooling",image:"/images/products/fans/fan-1.jpeg",cls:"object-contain p-8"},
{n:"03",kicker:"WE SUPPLY",title:"Buy with practical help nearby.",copy:"Laptops, appliances, power and audio from the same shop that understands how these products are used.",href:"/shop",image:"/images/products/laptops/laptop-3.jpeg",cls:"object-contain p-8"}
];
export function WeFixServiceSupply(){return <section className="relative overflow-hidden bg-obsidian text-off-white"><div className="absolute inset-0 blueprint-grid opacity-[.1]"/><div className="relative mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><Reveal><div className="grid gap-8 md:grid-cols-[.85fr_1.15fr]"><div><div className="section-kicker">The Magnanimous system</div><h2 className="mt-5 font-display text-5xl font-semibold leading-[.92] tracking-[-.05em] md:text-7xl">One shop.<br/>Three ways to keep things running.</h2></div><p className="self-end max-w-md text-base leading-relaxed text-off-white/55">Repair when the problem can be solved. Service when equipment needs attention. Supply when it is time for something new.</p></div></Reveal><Reveal delay={0.08}><div className="mt-14 grid gap-4 md:grid-cols-12">{panels.map((p,i)=><Link key={p.n} href={p.href} className={`group relative overflow-hidden border border-white/10 bg-navy-2 ${i===0?"min-h-[520px] md:col-span-6":"min-h-[330px] md:col-span-3"}`}><div className="absolute inset-0"><Image src={p.image} alt="" fill sizes="(min-width:768px) 50vw,100vw" className={`${p.cls} transition duration-700 image-luxury`}/><div className="absolute inset-0 bg-gradient-to-t from-obsidian via-obsidian/55 to-transparent"/></div><div className="relative flex h-full flex-col justify-between p-6 md:p-8"><div className="flex items-center justify-between font-mono text-[10px] tracking-[.2em] text-blue-bright"><span>{p.n}</span><ArrowUpRight size={16}/></div><div><div className="font-mono text-[10px] uppercase tracking-[.2em] text-blue-bright">{p.kicker}</div><h3 className="mt-4 max-w-sm font-display text-3xl font-semibold leading-tight tracking-tight">{p.title}</h3><p className="mt-4 max-w-sm text-sm leading-relaxed text-off-white/60">{p.copy}</p></div></div></Link>)}</div></Reveal></div></section>}
